apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: gpu-provisioner
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - g5.xlarge
        - g5.2xlarge
  labels:
    provisioner: gpu
  ttlSecondsAfterEmpty: 30
  limits:
    resources:
      cpu: "200"
